import type { Ingredient } from './ingredient'
import type { Picture } from './picture'
import type { User } from './user'

export interface Post {
  id: string // UUID or autogenerated string
  linkVideo: string
  title: string
  description: string
  likeCount: number
  dislikeCount: number
  tutorial: string
  ingredients: Ingredient[] // Array of Ingredient objects
  pictures: Picture[] // Array of Picture objects
  user: User // ManyToOne relationship with User
}
