export * from './auth'
export * from './home'
export * from './profile'
export * from './quiz'
export * from './about'
export * from './admin'
export * from './pagenotfound'
export * from './demoapi' 